version: '3'
services:
  database:
    image: 'postgres'
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file:
        - ./.env
    restart: always
    ports:
      - "8080:80"
    volumes:
       - pgadmin:/var/lib/pgadmin
volumes:
  postgresql:
  pgadmin:
