version: '3.0'
services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - database.env
    ports:
      - 3306:3306
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080